### ISSUE TITLE
Doesn't work with / in db names

### ISSUE THREAD

**Issue by bernharduw** [RipcordSoftware/avancedb-replication-monitor#40]
The replication monitor doesn't accept slashes in database names, e.g. 'analytics/app'. Database names should be url-encoded (`encodeURIComponent()` in JS).

![image](https://cloud.githubusercontent.com/assets/740978/23338584/3589f25a-fc0f-11e6-9830-bec662ec6f57.png)

**Comment by craigminihan** [comment]
Resolved in b781f462c56671702beef1f87c51bf4b88f4d561.

@bernharduw you can upgrade by running `brew install replication-monitor` again.

**Comment by bernharduw** [comment]
Works great, thanks a lot! (I used `brew upgrade replication-monitor` instead)
